### ISSUE TITLE
Could you please help to upgrade the Apache & PHP to latest version timely? 

### ISSUE THREAD

**Issue by ScottHuangZL** [ApacheFriends/xampp-build#2]
Hi ApacheFriends Team,

Current Xampp version is Apache 2.4.53  & PHP 7.4.29.
Could you hep to upgrade to Apache 2.4.54  & PHP 7.4.30?  It would reduce vulnerabilities risks and improve security level. Thanks.

Regards,
Scott Huang

**Comment by ScottHuangZL** [comment]
@beltran-rubo  Could you kindly help to upgrade Xampp key components to latest version to reduce vulnerabilities risks? Thanks for your support in advance.

https://www.apachefriends.org/download.html

**Comment by ScottHuangZL** [comment]
Anyway, I find a way to upgrade Apache(2.4.54)/OpenSSL(1.1.1p)/Php(7.4.30) to latest version in Xampp by myself. But it is better for ApacheFriends to upgrade the suite for more people, thanks.

**Comment by beltran-rubo** [comment]
Thanks @ScottHuangZL, just created a PR for updating main components.

**Comment by beltran-rubo** [comment]
XAMPP for Windows 8.1.10, 8.0.23 and 7.4.30 are available for testing [here](https://sourceforge.net/projects/xampp/files/BETAS/). Any feedback will be welcome.

**Comment by beltran-rubo** [comment]
XAMPP for Linux 8.1.10 and 8.0.23 are also available for testing [here](https://sourceforge.net/projects/xampp/files/BETAS/).

**Comment by beltran-rubo** [comment]
New versions available for Windows and Linux at https://www.apachefriends.org/download.html

**Comment by ScottHuangZL** [comment]
Thank you @beltran-rubo
