### ISSUE TITLE
Wrong windows portable zip package for 8.1.17

### ISSUE THREAD

**Issue by stronk7** [ApacheFriends/xampp-build#21]
Hi,

it seems that, within the new PHP 8.1.17 windows packages releases recently, the portable zip file is incorrect and using PHP 8.0, instead of PHP 8.1). At very least, the name (I've not checked for contents).

Link: https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/8.1.17/

It's showing [xampp-portable-windows-x64-8.0.28-0-VS16.zip](https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/8.1.17/xampp-portable-windows-x64-8.0.28-0-VS16.zip/download) and it should be `8.1`,  like all the other files in the directory.

Ciao :-)

**Comment by beltran-rubo** [comment]
Fixed thanks!
