### ISSUE TITLE
Outdated references to CakePHP & its App package

### ISSUE THREAD

**Issue by ravage84** [ApacheFriends/xampp-build#26]
By accident, I stumpled uplon these outdated referencess to the [CakePHP framework](https://github.com/cakephp/cakephp/) & [its app](https://github.com/cakephp/app) package.

https://github.com/ApacheFriends/xampp-build/blob/c4fad62c31e91ce8a404ef4858ad1be207f90d86/tools/vtracker/frameworks#L13-L22

Why are these included in the XAMPP builder?
Could they be updated to  current versions?

https://github.com/cakephp/cakephp/releases
https://github.com/cakephp/app/releases

If not, could these references be removed?

Disclaimer: I'm a core member of CakePHP.

**Comment by beltran-rubo** [comment]
Sorry for the delay, yes we can drop that reference, thanks for the heads up.
