### ISSUE TITLE
PHP 8.4.x support?

### ISSUE THREAD

**Issue by Neustradamus** [ApacheFriends/xampp-build#40]
Dear @ApacheFriends team,

PHP 8.4.1 has been released (2024-11-21).

Currently, there is one year without any changes, the XAMPP project is now dead?

Thanks in advance.

**Comment by beltran-rubo** [comment]
Thanks, the project is not dead but looking for contributions to manage those updates in a timely manner. The code is OS and any contribution will be welcome. PHP 8.4 will require a new installer as well as it is a major version. We plan a new release beginning next year.

**Comment by Neustradamus** [comment]
@beltran-rubo: Can you reopen, the PHP 8.4.x support has not been added.

Thanks in advance.

**Comment by Neustradamus** [comment]
At this time: PHP 8.4.18 (2026-02-12):
- https://www.php.net/archive/2026.php#2026-02-12-1
